apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: default
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
  - '--debug'
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws
spec:
  package: crossplane/provider-aws:v0.32.0
controllerConfigRef:
  name: default

