apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: production-vpc
spec:
  forProvider:
    region: eu-west-2
    cidrBlock: 10.0.0.0/24
    enableDnsSupport: true
    enableDnsHostNames: true
    tags:
    - key: Environment
      value: Production
    - key: ManagedBy
      value: Crossplane
    instanceTenancy: default
  providerConfigRef:
    name: default
